Bump async-std from 1.6.5 to 1.7.0 (#1510)
Bumps [async-std](https://github.com/async-rs/async-std) from 1.6.5 to 1.7.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/async-rs/async-std/releases">async-std's releases</a>.</em></p>
<blockquote>
<h2>v1.7.0</h2>
<p><a href="https://docs.rs/async-std/1.7.0/async_std/">docs.rs documentation</a></p>
<p>This patch adds a feature to enable compatibility with the new <code>tokio</code> 0.3.0 release, and updates internal dependencies.</p>
<h2>Tokio 0.3.x compat</h2>
<p>Since earlier this year <code>async-std</code> has shipped with a <code>tokio-02</code> feature flag that enables libraries written for the <code>tokio</code> runtime to work on <code>async-std</code> as well. When this flag is enabled <code>async-std</code> ensures that whenever it spawns a thread on its executor, the right tokio-specific thread state is initialized for it. That means no more <code>thread 'main' panicked at 'not currently running on the Tokio runtime.'</code> errors when running <code>async-std</code> and <code>tokio</code> in the same application.</p>
<p>This patch introduces a new feature flag: <code>tokio-03</code> which enables the same mechanism for the latest version of the <code>tokio</code> runtime. As applications migrate from <code>tokio</code> 0.2.x to 0.3.x, mixing dependencies that use both <code>async-std</code> and <code>tokio</code> will continue to work.</p>
<h2>Added</h2>
<ul>
<li>Add <code>tokio03</code> feature flag (<a href="https://github-redirect.dependabot.com/async-rs/async-std/pull/895">#895</a>)</li>
</ul>
<h2>Internal</h2>
<ul>
<li>chore: update dependencies (<a href="https://github-redirect.dependabot.com/async-rs/async-std/pull/897">#897</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/async-rs/async-std/blob/master/CHANGELOG.md">async-std's changelog</a>.</em></p>
<blockquote>
<h1>[1.7.0] - 2020-10-30</h1>
<p>This patch adds a feature to enable compatibility with the new <code>tokio</code> 0.3.0
release, and updates internal dependencies.</p>
<h2>Added</h2>
<ul>
<li>Add <code>tokio03</code> feature (<a href="https://github-redirect.dependabot.com/async-rs/async-std/pull/895">#895</a>)</li>
</ul>
<h2>Internal</h2>
<ul>
<li>chore: update dependencies (<a href="https://github-redirect.dependabot.com/async-rs/async-std/pull/897">#897</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/async-rs/async-std/commit/0f50f3c978775459bbcdb64701d5feb48f1a18de"><code>0f50f3c</code></a> Merge pull request <a href="https://github-redirect.dependabot.com/async-rs/async-std/issues/902">#902</a> from async-rs/v1.7.0</li>
<li><a href="https://github.com/async-rs/async-std/commit/ca84dbdd4090439410605a8a269a3f4f8be4fbce"><code>ca84dbd</code></a> v1.7.0</li>
<li><a href="https://github.com/async-rs/async-std/commit/11196c853dc42e86d608c4ed29af1a8f0c5c5084"><code>11196c8</code></a> chore: update dependencies</li>
<li><a href="https://github.com/async-rs/async-std/commit/cc4bb943b00aee6ce8a02310819fb903df8967ad"><code>cc4bb94</code></a> Merge pull request <a href="https://github-redirect.dependabot.com/async-rs/async-std/issues/895">#895</a> from Keruspe/tokio03</li>
<li><a href="https://github.com/async-rs/async-std/commit/a5f72f140fa239f760c0ab9a03c36784978564fa"><code>a5f72f1</code></a> add tokio03 feature</li>
<li>See full diff in <a href="https://github.com/async-rs/async-std/compare/v1.6.5...v1.7.0">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://api.dependabot.com/badges/compatibility_score?dependency-name=async-std&package-manager=cargo&previous-version=1.6.5&new-version=1.7.0)](https://dependabot.com/compatibility-score/?dependency-name=async-std&package-manager=cargo&previous-version=1.6.5&new-version=1.7.0)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)
- `@dependabot use these labels` will set the current labels as the default for future PRs for this repo and language
- `@dependabot use these reviewers` will set the current reviewers as the default for future PRs for this repo and language
- `@dependabot use these assignees` will set the current assignees as the default for future PRs for this repo and language
- `@dependabot use this milestone` will set the current milestone as the default for future PRs for this repo and language
- `@dependabot badge me` will comment on this PR with code to add a "Dependabot enabled" badge to your readme

Additionally, you can set the following in your Dependabot [dashboard](https://app.dependabot.com):
- Update frequency (including time of day and day of week)
- Pull request limits (per update run and/or open at any time)
- Out-of-range updates (receive only lockfile updates, if desired)
- Security updates (receive only security updates, if desired)



</details>